### ISSUE TITLE
Missing Channel Section From LiveTV

### ISSUE THREAD

**Issue by AetherVoyager** [ValerioLyndon/Rockfin#2]
![image](https://github.com/ValerioLyndon/Rockfin/assets/164147656/1c32389d-11e0-41f9-b2d4-e0db123b7d91)

On Jellyfin Desktop Client

**Comment by ValerioLyndon** [comment]
Should be fixed now, thanks for the report!

The issue was caused by a legacy personal tweak I forgot to remove plus the fact I'd never set up LiveTV.
